version: 0.2

env:
  variables:
    CODEARTIFACT_DOMAIN: yadayada
    CODEARTIFACT_REPOSITORY: yadayada-master-deploy
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    commands:
      - NORMALIZED_BRANCH=${Branch/\//\-}
      - dotnet tool install -g amazon.lambda.tools
      - TOKEN=`aws codeartifact get-authorization-token  --domain $CODEARTIFACT_DOMAIN --query authorizationToken --output text`
      - LIB_ENDPOINT=`aws codeartifact get-repository-endpoint --domain $CODEARTIFACT_DOMAIN --repository $CODEARTIFACT_REPOSITORY --format nuget --output text`
      - LIB_ENDPOINT="${LIB_ENDPOINT}v3/index.json"
      - dotnet nuget add source --name $CODEARTIFACT_REPOSITORY --username aws --password $TOKEN --store-password-in-clear-text $LIB_ENDPOINT
      - export PATH="$PATH:/root/.dotnet/tools"
      - printenv
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - VERSION="0.5.1-preview-$CODEBUILD_BUILD_NUMBER-$NORMALIZED_BRANCH"
      - dotnet build -c $CONFIGURATION 
      - dotnet pack -c $CONFIGURATION Foundation.Annotations
      - dotnet lambda package-ci Foundation.Functions --s3-bucket $BUCKET --template Foundation.Functions/serverless.template --output-template Foundation.Functions/serverless.template
  post_build:
    commands:
      - dotnet nuget push **/*.nupkg --source $LIB_ENDPOINT
      # - command
#reports:
    #tests:
        #file-format: VisualStudioTrx
        #files:
            #- '**/*.trx'
        #base-directory: $CODEBUILD_SRC_DIR/TestResults
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths